### ISSUE TITLE
Time frequency for EEG Signal does not work

### ISSUE THREAD

**Issue by niroigen** [abuebola/sensobox#74]

**Comment by niroigen** [comment]
Traceback (most recent call last):
  File "/home/niroigen/Dev/sensomatrix/src/sensobox/widgets/main_window.py", line 110, in plot_time_freq_secondary
    self.ui.secondary_area.plot_tf_slot(signal)
  File "/home/niroigen/Dev/sensomatrix/src/sensobox/widgets/secondaryarea.py", line 33, in plot_tf_slot
    self.tf_dock.plot_TF(signal)
  File "/home/niroigen/Dev/sensomatrix/src/sensobox/widgets/graphdock.py", line 45, in plot_TF
    TFf, TFt, TFSxx = compute_time_freq(signal.samples_array, signal.fs)
AttributeError: 'Signal' object has no attribute 'samples_array'
